import { withSupabase } from "npm:@supabase/server";
import { extractText, getDocumentProxy } from "npm:unpdf@1.8.1";
const STAGES=["validate_file","extract_text_ocr","analyze_structure","detect_chapters","extract_metadata","generate_summaries","characters_glossary","generate_embeddings","human_review","publish"];
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
async function stage(admin,jobId,key,status,progress,metadata={}){const patch={status,progress_percent:Math.max(0,Math.min(100,progress)),metadata};if(status==="running")patch.started_at=new Date().toISOString();if(["completed","failed","skipped"].includes(status))patch.finished_at=new Date().toISOString();await admin.from("processing_job_stages").update(patch).eq("job_id",jobId).eq("stage_key",key);}
async function log(admin,jobId,level,message,metadata={}){await admin.from("processing_job_logs").insert({job_id:jobId,level,message,metadata});}
async function prog(admin,jobId,current_stage,progress_percent){await admin.from("processing_jobs").update({current_stage,progress_percent,updated_at:new Date().toISOString()}).eq("id",jobId);}
function parseJson(text){const s=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");try{return JSON.parse(s);}catch{}const o=s.match(/\{[\s\S]*\}/);if(o){try{return JSON.parse(o[0]);}catch{}}const a=s.match(/\[[\s\S]*\]/);if(a){try{return JSON.parse(a[0]);}catch{}}return null;}
function slug(value){return String(value||"chapter").normalize("NFKD").replace(/[^\w\s-]/g,"").trim().toLowerCase().replace(/[-\s]+/g,"-").replace(/^-+|-+$/g,"").slice(0,100)||"chapter";}
function heuristic(pages){const found=[];for(let i=0;i<pages.length;i++){const lines=pages[i].split(/\r?\n/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean).slice(0,8);for(const line of lines){const m=line.match(/^(chapter|chap\.?|episode|part)\s+([0-9IVXLC]+)\s*[-:.)]?\s*(.*)$/i)||line.match(/^(prologue|epilogue|interlude)(?:\s*[-:.)]\s*(.*))?$/i);if(!m)continue;if(!found.some(x=>x.start_page===i+1))found.push({number:Number.parseInt(m[2],10)||found.length+1,title:line.slice(0,180),start_page:i+1});break;}}return found.length?found:[{number:1,title:"Chapter 1",start_page:1}];}
async function ai(apiKey,model,input,max_output_tokens=4000){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:"Bearer "+apiKey,"Content-Type":"application/json"},body:JSON.stringify({model,input,max_output_tokens,store:false})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"OpenAI request failed.");return String(p?.output_text||"");}
async function embed(apiKey,input){const r=await fetch("https://api.openai.com/v1/embeddings",{method:"POST",headers:{Authorization:"Bearer "+apiKey,"Content-Type":"application/json"},body:JSON.stringify({model:"text-embedding-3-small",input,encoding_format:"float"})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Embedding request failed.");return (p?.data||[]).sort((a,b)=>a.index-b.index).map(x=>x.embedding);}
function makeChunks(text){const s=String(text||"").replace(/\s+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();const out=[];let start=0;while(start<s.length){let end=Math.min(s.length,start+1500);if(end<s.length){const b=Math.max(s.lastIndexOf(" ",end),s.lastIndexOf("\n",end));if(b>start+900)end=b;}const part=s.slice(start,end).trim();if(part.length>=120)out.push(part);if(end>=s.length)break;start=Math.max(0,end-200);}return out;}
async function ocr(apiKey,model,url,from,to){const prompt="Extract readable text from PDF pages "+from+"-"+to+". Return JSON with a pages array; each item must contain page_number and content. Preserve paragraph breaks. Do not summarize or invent.";return parseJson(await ai(apiKey,model,[{role:"user",content:[{type:"input_file",file_url:url,detail:"high"},{type:"input_text",text:prompt}]}],12000));}
Deno.serve(withSupabase({auth:"user"},async(req,ctx)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders}); let jobId=""; let stageName="";
 try{
  const body=await req.json();jobId=typeof body?.job_id==="string"?body.job_id:"";if(!jobId)return Response.json({error:"job_id is required."},{status:400,headers:corsHeaders});
  const {data:role}=await ctx.supabaseAdmin.schema("private").from("user_roles").select("role").eq("user_id",ctx.userClaims?.id).maybeSingle();if(!["editor","admin"].includes(role?.role))return Response.json({error:"Editor or admin role required."},{status:403,headers:corsHeaders});
  const {data:job,error:je}=await ctx.supabaseAdmin.from("processing_jobs").select("id,volume_id,input_path,file_size_bytes").eq("id",jobId).maybeSingle();if(je)throw je;if(!job?.volume_id)return Response.json({error:"Processing job or volume not found."},{status:404,headers:corsHeaders});
  const {data:volume,error:ve}=await ctx.supabaseAdmin.from("volumes").select("id,novel_id,volume_number,title,subtitle,metadata").eq("id",job.volume_id).maybeSingle();if(ve)throw ve;if(!volume)throw new Error("Volume not found.");
  const {data:novel,error:ne}=await ctx.supabaseAdmin.from("novels").select("id,title,alternate_title,author,description,genres,language,publication_status").eq("id",volume.novel_id).maybeSingle();if(ne)throw ne;if(!novel)throw new Error("Novel not found.");
  await ctx.supabaseAdmin.from("processing_job_stages").upsert(STAGES.map((stage_key,i)=>({job_id:jobId,stage_order:i+1,stage_key,status:"waiting",progress_percent:0})),{onConflict:"job_id,stage_key",ignoreDuplicates:false});
  await ctx.supabaseAdmin.from("processing_jobs").update({status:"processing",current_stage:"Validate file",progress_percent:1,started_at:new Date().toISOString(),finished_at:null,error_message:null}).eq("id",jobId);
  await ctx.supabaseAdmin.from("volumes").update({publication_status:"processing"}).eq("id",volume.id);if(novel.publication_status!=="published")await ctx.supabaseAdmin.from("novels").update({publication_status:"processing"}).eq("id",novel.id);
  await log(ctx.supabaseAdmin,jobId,"info","Starting full PDF ingestion.",{version:4});
  stageName="Validate file";await prog(ctx.supabaseAdmin,jobId,stageName,1);await stage(ctx.supabaseAdmin,jobId,"validate_file","running",25);
  const {data:file,error:fe}=await ctx.supabaseAdmin.storage.from("novel-pdfs").download(job.input_path);if(fe||!file)throw fe||new Error("Unable to download PDF.");
  const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length<5||new TextDecoder().decode(bytes.slice(0,5))!=="%PDF-")throw new Error("The uploaded file is not a valid PDF.");if(bytes.length>500*1024*1024)throw new Error("PDF exceeds the 500 MB ingestion limit.");
  const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");await ctx.supabaseAdmin.from("volumes").update({pdf_sha256:hash}).eq("id",volume.id);await stage(ctx.supabaseAdmin,jobId,"validate_file","completed",100,{bytes:bytes.length,sha256:hash});
  stageName="Extract text & OCR";await prog(ctx.supabaseAdmin,jobId,stageName,8);await stage(ctx.supabaseAdmin,jobId,"extract_text_ocr","running",10);
  const pdf=await getDocumentProxy(bytes);const extracted=await extractText(pdf,{mergePages:false});let pages=Array.isArray(extracted.text)?extracted.text.map(x=>String(x||"")):String(extracted.text||"").split("\\f");if(!pages.length)throw new Error("No pages could be extracted from the PDF.");
  const apiKey=Deno.env.get("OPENAI_API_KEY")||"";const model=Deno.env.get("OPENAI_MODEL")||"gpt-5";let ocrUsed=false;const nonEmpty=pages.filter(x=>x.trim().length>40).length;
  if(nonEmpty<Math.max(1,Math.floor(pages.length*0.25))&&apiKey&&bytes.length<=50*1024*1024){const signed=await ctx.supabaseAdmin.storage.from("novel-pdfs").createSignedUrl(job.input_path,3600);if(signed.error||!signed.data?.signedUrl)throw signed.error||new Error("Unable to create signed PDF URL for OCR.");for(let from=1;from<=pages.length;from+=12){const to=Math.min(pages.length,from+11);const data=await ocr(apiKey,model,signed.data.signedUrl,from,to);for(const p of (data?.pages||[])){if(Number.isInteger(p.page_number)&&typeof p.content==="string"&&p.page_number>=1&&p.page_number<=pages.length)pages[p.page_number-1]=p.content;}}ocrUsed=true;await log(ctx.supabaseAdmin,jobId,"ai","OCR fallback completed.",{pages:pages.length});}
  await stage(ctx.supabaseAdmin,jobId,"extract_text_ocr","completed",100,{total_pages:pages.length,ocr_used:ocrUsed});
  stageName="Analyze structure";await prog(ctx.supabaseAdmin,jobId,stageName,18);await stage(ctx.supabaseAdmin,jobId,"analyze_structure","running",10);let structure=null;
  const pageIndex=pages.map((p,i)=>"P"+(i+1)+": "+p.replace(/\s+/g," ").slice(0,150)).join("\n").slice(0,140000);
  if(apiKey){try{structure=parseJson(await ai(apiKey,model,"Identify chapter boundaries from this page index. Return a JSON object with a chapters array. Each chapter needs number, title, start_page and end_page. Use exact page numbers and ignore table-of-contents entries when possible.\n\n"+pageIndex,8000));}catch(e){await log(ctx.supabaseAdmin,jobId,"warn","AI structure analysis failed; using heading detection.",{error:String(e)});}}
  await stage(ctx.supabaseAdmin,jobId,"analyze_structure","completed",100,{provider:structure?"openai":"heuristic",model});
  stageName="Detect chapters";await prog(ctx.supabaseAdmin,jobId,stageName,28);await stage(ctx.supabaseAdmin,jobId,"detect_chapters","running",10);
  let defs=Array.isArray(structure?.chapters)?structure.chapters.filter(c=>Number.isInteger(c.start_page)).map((c,i)=>({number:Number.isInteger(c.number)&&c.number>0?c.number:i+1,title:typeof c.title==="string"&&c.title.trim()?c.title.trim().slice(0,180):"Chapter "+(i+1),start_page:Math.max(1,Math.min(pages.length,c.start_page)),end_page:Number.isInteger(c.end_page)?Math.max(1,Math.min(pages.length,c.end_page)):pages.length})):[];
  if(!defs.length){const h=heuristic(pages);defs=h.map((c,i)=>({number:c.number,title:c.title,start_page:c.start_page,end_page:i+1<h.length?h[i+1].start_page-1:pages.length}));}defs=defs.sort((a,b)=>a.start_page-b.start_page).map((c,i,arr)=>({...c,end_page:Math.min(c.end_page,i+1<arr.length?arr[i+1].start_page-1:pages.length)}));if(!defs.length)defs=[{number:1,title:"Chapter 1",start_page:1,end_page:pages.length}];
  const {data:old}=await ctx.supabaseAdmin.from("chapters").select("id").eq("volume_id",volume.id);const oldIds=(old||[]).map(x=>x.id);if(oldIds.length){await ctx.supabaseAdmin.from("chapter_chunks").delete().in("chapter_id",oldIds);await ctx.supabaseAdmin.from("chapter_characters").delete().in("chapter_id",oldIds);await ctx.supabaseAdmin.from("chapter_pages").delete().in("chapter_id",oldIds);await ctx.supabaseAdmin.from("chapters").delete().in("id",oldIds);}
  const chapters=[];for(let i=0;i<defs.length;i++){const c=defs[i];const {data,error}=await ctx.supabaseAdmin.from("chapters").insert({volume_id:volume.id,chapter_number:c.number,title:c.title,slug:slug(c.title)+"-"+c.number,start_page:c.start_page,end_page:c.end_page,word_count:0,content_format:"text",publication_status:"draft"}).select("id,chapter_number,title,start_page,end_page").single();if(error)throw error;chapters.push(data);}await stage(ctx.supabaseAdmin,jobId,"detect_chapters","completed",100,{chapter_count:chapters.length});
  stageName="Extract metadata";await prog(ctx.supabaseAdmin,jobId,stageName,35);await stage(ctx.supabaseAdmin,jobId,"extract_metadata","running",10);let meta=null;
  if(apiKey){try{const sample=pages.map((p,i)=>"PAGE "+(i+1)+"\n"+p.slice(0,700)).join("\n\n").slice(0,70000);meta=parseJson(await ai(apiKey,model,"Analyze this light-novel volume. Return a JSON object with document_title, alternate_title, author, language, genres and synopsis. Do not invent facts. Synopsis must be spoiler-safe and concise.\n\n"+sample,3000));}catch(e){await log(ctx.supabaseAdmin,jobId,"warn","Metadata AI pass failed.",{error:String(e)});}}
  await ctx.supabaseAdmin.from("volumes").update({page_count:pages.length,metadata:{...(volume.metadata||{}),ingestion:{version:4,processed_at:new Date().toISOString(),total_pages:pages.length,chapter_count:chapters.length,ocr_used:ocrUsed,sha256:hash},ai_intake:meta}}).eq("id",volume.id);
  const patch={};if(!novel.author&&meta?.author)patch.author=String(meta.author).slice(0,200);if(!novel.alternate_title&&meta?.alternate_title)patch.alternate_title=String(meta.alternate_title).slice(0,240);if(!novel.description&&meta?.synopsis)patch.description=String(meta.synopsis).slice(0,1200);if((!novel.genres||!novel.genres.length)&&Array.isArray(meta?.genres))patch.genres=meta.genres.map(x=>String(x).trim()).filter(Boolean).slice(0,12);if(Object.keys(patch).length)await ctx.supabaseAdmin.from("novels").update(patch).eq("id",novel.id);await stage(ctx.supabaseAdmin,jobId,"extract_metadata","completed",100,{ai_used:Boolean(meta)});
  stageName="Write extracted pages";await prog(ctx.supabaseAdmin,jobId,stageName,45);
  for(let offset=0;offset<pages.length;offset+=100){const batch=pages.slice(offset,offset+100).map((content,j)=>{const source=offset+j+1;const c=chapters.find(x=>source>=x.start_page&&source<=x.end_page)||chapters.at(-1);return{chapter_id:c.id,page_number:source-c.start_page+1,source_pdf_page:source,content:content.trim(),ocr_used:ocrUsed,extraction_confidence:content.trim().length>40?0.98:content.trim().length?0.7:0,layout:{extracted:true}};});const {error}=await ctx.supabaseAdmin.from("chapter_pages").insert(batch);if(error)throw error;await prog(ctx.supabaseAdmin,jobId,stageName,45+Math.round(((offset+batch.length)/pages.length)*12));}
  for(const c of chapters){const wc=pages.slice(c.start_page-1,c.end_page).join(" ").trim().split(/\s+/).filter(Boolean).length;await ctx.supabaseAdmin.from("chapters").update({word_count:wc}).eq("id",c.id);}
  stageName="Generate summaries";await prog(ctx.supabaseAdmin,jobId,stageName,60);await stage(ctx.supabaseAdmin,jobId,"generate_summaries","running",5);
  if(apiKey){try{const input=chapters.slice(0,32).map(c=>"CHAPTER "+c.chapter_number+" — "+c.title+"\n"+pages.slice(c.start_page-1,c.end_page).join("\n\n").slice(0,5000)).join("\n\n");const sum=parseJson(await ai(apiKey,model,"Create spoiler-safe summaries. Return a JSON object with a summaries array containing chapter_number and summary.\n\n"+input,6000));for(const item of (sum?.summaries||[])){const c=chapters.find(x=>x.chapter_number===item.chapter_number);if(c&&typeof item.summary==="string")await ctx.supabaseAdmin.from("chapters").update({summary:item.summary,spoiler_safe_summary:item.summary}).eq("id",c.id);}}catch(e){await log(ctx.supabaseAdmin,jobId,"warn","Summary AI pass failed.",{error:String(e)});}}
  await stage(ctx.supabaseAdmin,jobId,"generate_summaries","completed",100,{ai_used:Boolean(apiKey)});
  stageName="Characters & glossary";await prog(ctx.supabaseAdmin,jobId,stageName,68);await stage(ctx.supabaseAdmin,jobId,"characters_glossary","running",5);let knowledge=null;
  if(apiKey){try{knowledge=parseJson(await ai(apiKey,model,"Build a spoiler-safe knowledge index. Return a JSON object with characters and glossary arrays. Character fields: canonical_name, aliases, short_description, spoiler_safe_description, first_appearance_chapter. Glossary fields: term, definition, spoiler_safe_definition, first_appearance_chapter. Use only supported facts.\n\n"+pages.join("\n\n").slice(0,90000),9000));}catch(e){await log(ctx.supabaseAdmin,jobId,"warn","Knowledge AI pass failed.",{error:String(e)});}}
  for(const item of (knowledge?.characters||[]).slice(0,40)){if(typeof item?.canonical_name!=="string"||!item.canonical_name.trim())continue;const name=item.canonical_name.trim().slice(0,200);const {data:existing}=await ctx.supabaseAdmin.from("characters").select("id").eq("novel_id",novel.id).eq("canonical_name",name).maybeSingle();const values={novel_id:novel.id,canonical_name:name,aliases:Array.isArray(item.aliases)?item.aliases.map(x=>String(x)).slice(0,20):[],short_description:typeof item.short_description==="string"?item.short_description.slice(0,600):null,spoiler_safe_description:typeof item.spoiler_safe_description==="string"?item.spoiler_safe_description.slice(0,600):null,first_appearance_volume:volume.volume_number,first_appearance_chapter:Number.isInteger(item.first_appearance_chapter)?item.first_appearance_chapter:1,metadata:{source:"ai-ingestion",volume_id:volume.id}};if(existing?.id)await ctx.supabaseAdmin.from("characters").update(values).eq("id",existing.id);else await ctx.supabaseAdmin.from("characters").insert(values);}
  for(const item of (knowledge?.glossary||[]).slice(0,60)){if(typeof item?.term!=="string"||!item.term.trim())continue;const term=item.term.trim().slice(0,240);const {data:existing}=await ctx.supabaseAdmin.from("glossary_terms").select("id").eq("novel_id",novel.id).eq("term",term).maybeSingle();const values={novel_id:novel.id,term,definition:typeof item.definition==="string"?item.definition.slice(0,1000):"",spoiler_safe_definition:typeof item.spoiler_safe_definition==="string"?item.spoiler_safe_definition.slice(0,1000):null,first_appearance_volume:volume.volume_number,first_appearance_chapter:Number.isInteger(item.first_appearance_chapter)?item.first_appearance_chapter:1,metadata:{source:"ai-ingestion",volume_id:volume.id}};if(existing?.id)await ctx.supabaseAdmin.from("glossary_terms").update(values).eq("id",existing.id);else await ctx.supabaseAdmin.from("glossary_terms").insert(values);}
  await stage(ctx.supabaseAdmin,jobId,"characters_glossary","completed",100,{characters:knowledge?.characters?.length||0,glossary:knowledge?.glossary?.length||0});
  stageName="Generate embeddings";await prog(ctx.supabaseAdmin,jobId,stageName,78);await stage(ctx.supabaseAdmin,jobId,"generate_embeddings","running",5);
  if(apiKey){for(let ci=0;ci<chapters.length;ci++){const c=chapters[ci];const list=makeChunks(pages.slice(c.start_page-1,c.end_page).join("\n\n"));for(let i=0;i<list.length;i+=48){const texts=list.slice(i,i+48);const vecs=await embed(apiKey,texts);const rows=texts.map((content,k)=>({chapter_id:c.id,chunk_index:i+k,content,token_count:Math.ceil(content.length/4),embedding:"["+vecs[k].join(",")+"]",metadata:{volume_id:volume.id,source:"ai-ingestion"}}));const {error}=await ctx.supabaseAdmin.from("chapter_chunks").insert(rows);if(error)throw error;}await prog(ctx.supabaseAdmin,jobId,stageName,78+Math.round(((ci+1)/chapters.length)*10));await stage(ctx.supabaseAdmin,jobId,"generate_embeddings","running",Math.round(((ci+1)/chapters.length)*100));}await stage(ctx.supabaseAdmin,jobId,"generate_embeddings","completed",100,{dimensions:1536});}else{await stage(ctx.supabaseAdmin,jobId,"generate_embeddings","skipped",100,{reason:"OPENAI_API_KEY missing"});}
  stageName="Human review";await prog(ctx.supabaseAdmin,jobId,stageName,90);await stage(ctx.supabaseAdmin,jobId,"human_review","running",0,{ready:true,chapter_count:chapters.length,total_pages:pages.length});
  await ctx.supabaseAdmin.from("volumes").update({publication_status:"review"}).eq("id",volume.id);if(novel.publication_status!=="published")await ctx.supabaseAdmin.from("novels").update({publication_status:"review"}).eq("id",novel.id);await ctx.supabaseAdmin.from("processing_jobs").update({status:"review",current_stage:"Human review",progress_percent:90,finished_at:new Date().toISOString()}).eq("id",jobId);
  await log(ctx.supabaseAdmin,jobId,"info","PDF ingestion completed and is ready for review.",{pages:pages.length,chapters:chapters.length});return Response.json({ok:true,job_id:jobId,status:"review",progress_percent:90,page_count:pages.length,chapter_count:chapters.length},{headers:corsHeaders});
 }catch(error){const message=error instanceof Error?error.message:"Processing failed.";if(jobId){await ctx.supabaseAdmin.from("processing_jobs").update({status:"failed",current_stage:stageName||"Processing failed",error_message:message.slice(0,2000),finished_at:new Date().toISOString()}).eq("id",jobId);await log(ctx.supabaseAdmin,jobId,"error",message.slice(0,2000));}return Response.json({error:message},{status:500,headers:corsHeaders});}
}));